name: Run MATLAB Tests on GitHub-Hosted Runner
on:
  push:
    - '!Git_docs'
jobs:
  PECUZAL-test-job:
    name: Run MATLAB Tests for PECUZAL
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2020b
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('tests'), test_pecuzal
